name: firebase_food_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  firebase_core: 2.31.1
  firebase_auth: 4.19.6
  cloud_firestore: 4.17.4
  get_storage: ^2.1.1
  uuid: 4.4.0
  intl: 0.19.0
  cached_network_image: 3.3.1
  image_picker: 1.1.1
  flutter_native_splash: 2.4.0
  flutter_local_notifications: ^17.1.2
  flutter_native_timezone: ^2.0.0
  flutter_screenutil: ^5.9.1
  firebase_storage: 11.7.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
  uses-material-design: true

flutter_native_splash: 
  color: '#ffffff'
  image: assets/images/logo2.png
  color_dark: '#121212'
  image_dark: assets/images/logo2.png
  android_12: 
    image: assets/images/logo2.png
    icon_background_color: '#ffffff'
    image_dark: assets/images/logo2.png
    icon_background_color_dark: '#121212'
  web: false 

